// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "metadata": {
    "applicationName": "멘타"
  },

  "auth": {
    "result": {
      "fieldErrorCodes": {
        "email": {
          "invalid_format": "유효한 이메일을 입력해주세요."
        },

        "password": {
          "too_short": "비밀번호는 최소 {min}자 이상이어야 합니다.",
          "too_long": "비밀번호는 최대 {max}자 이하여야 합니다.",
          "missing_lowercase": "비밀번호는 최소 1개 이상의 소문자를 포함해야 합니다.",
          "missing_uppercase": "비밀번호는 최소 1개 이상의 대문자를 포함해야 합니다.",
          "missing_number": "비밀번호는 최소 1개 이상의 숫자를 포함해야 합니다.",
          "missing_special_char": "비밀번호는 최소 1개 이상의 특수문자를 포함해야 합니다."
        },

        "password_confirmation": {
          "mismatch": "비밀번호가 일치해야 합니다."
        }
      },

      "signupErrorCodes": {
        "user_already_exists": "가입된 적 없는 이메일을 입력해주세요."
      },

      "loginErrorCodes": {
        "invalid_credentials": "유효한 정보를 입력해주세요."
      }
    },

    "component": {
      "successCandy": {
        "title": "회원가입 완료",
        "warning": "하지만, 계정을 사용하려면 이메일 확인이 필요합니다.",
        "details": " 인증 코드를 가입하신 이메일({email})로 보내드렸습니다. 이메일을 확인해주세요."
      }
    }
  }
};
export default messages;